### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by CXVUSER** [Col-E/recaf-4x-rewrite-temp#2]
`Could not determine the dependencies of task ':recaf-ui:shadowJar'.
> Could not resolve all dependencies for configuration ':recaf-ui:runtimeClasspath'.
   > Could not find org.fxmisc.richtext:richtextfx:0.11.1.
     Searched in the following locations:
       - file:/C:/Users/vzheg/.m2/repository/org/fxmisc/richtext/richtextfx/0.11.1/richtextfx-0.11.1.pom
       - https://repo.maven.apache.org/maven2/org/fxmisc/richtext/richtextfx/0.11.1/richtextfx-0.11.1.pom
       - https://dl.google.com/dl/android/maven2/org/fxmisc/richtext/richtextfx/0.11.1/richtextfx-0.11.1.pom
       - https://jitpack.io/org/fxmisc/richtext/richtextfx/0.11.1/richtextfx-0.11.1.pom
       - https://maven.quiltmc.org/repository/release/org/fxmisc/richtext/richtextfx/0.11.1/richtextfx-0.11.1.pom
     Required by:
         project :recaf-ui
   > Could not find software.coley:dex-translator:1.1.1.
     Searched in the following locations:
       - file:/C:/Users/vzheg/.m2/repository/software/coley/dex-translator/1.1.1/dex-translator-1.1.1.pom
       - https://repo.maven.apache.org/maven2/software/coley/dex-translator/1.1.1/dex-translator-1.1.1.pom
       - https://dl.google.com/dl/android/maven2/software/coley/dex-translator/1.1.1/dex-translator-1.1.1.pom
       - https://jitpack.io/software/coley/dex-translator/1.1.1/dex-translator-1.1.1.pom
       - https://maven.quiltmc.org/repository/release/software/coley/dex-translator/1.1.1/dex-translator-1.1.1.pom
     Required by:
         project :recaf-ui > project :recaf-core > project :recaf-api`

**Comment by Col-E** [comment]
Bump dex-translator down to 1.1.0 and richtextfx to 0.11.0

I installed newer versions of those locally and accidentally pushed.

**Comment by Col-E** [comment]
Bumped down the dependencies
